[project]
name = "unicorn-api"
version = "0.1.0"
description = "stream data from a unicorn to websocket"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.113.0",
    "pandas>=2.2.2",
    "scipy>=1.14.1",
]
